export const hotelTypes = [
  "Luxury Hotel",
  "Boutique Hotel",
  "Business Hotel",
  "Resort",
  "Bed and Breakfast",
  "Budget Hotel",
  "Motel",
  "Hostel",
  "Apartment Hotel",
  "Extended Stay Hotel",
  "Spa Hotel",
  "Casino Hotel",
  "Airport Hotel",
  "All-Inclusive Resort",
  "Ecotourism Lodge",
  "Historic Hotel",
  "Floating Hotel",
  "Capsule Hotel",
  "Treehouse Hotel",
  "Underwater Hotel",
];

export const hotelFacilicities = [
  "Free Wi-Fi",
  "Swimming Pool",
  "Fitness Center",
  "Restaurant",
  "Room Service",
  "Conference Room",
  "Spa and Wellness Center",
  "Parking",
  "Pet-Friendly",
  "24-Hour Front Desk",
];
